// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compass.proto

/*
Package compass is a generated protocol buffer package.

It is generated from these files:
	compass.proto

It has these top-level messages:
	CreateCompassReleaseRequest
	CreateCompassReleaseResponse
*/
package compass

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hapi_release5 "k8s.io/helm/pkg/proto/hapi/release"
import hapi_chart "k8s.io/helm/pkg/proto/hapi/chart"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateCompassReleaseRequest struct {
	Chart     string             `protobuf:"bytes,1,opt,name=chart" json:"chart,omitempty"`
	Name      string             `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Namespace string             `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	Values    *hapi_chart.Config `protobuf:"bytes,4,opt,name=values" json:"values,omitempty"`
	Timeout   int64              `protobuf:"varint,5,opt,name=timeout" json:"timeout,omitempty"`
	Wait      bool               `protobuf:"varint,6,opt,name=wait" json:"wait,omitempty"`
}

func (m *CreateCompassReleaseRequest) Reset()                    { *m = CreateCompassReleaseRequest{} }
func (m *CreateCompassReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCompassReleaseRequest) ProtoMessage()               {}
func (*CreateCompassReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateCompassReleaseRequest) GetChart() string {
	if m != nil {
		return m.Chart
	}
	return ""
}

func (m *CreateCompassReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCompassReleaseRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateCompassReleaseRequest) GetValues() *hapi_chart.Config {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *CreateCompassReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *CreateCompassReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

type CreateCompassReleaseResponse struct {
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *CreateCompassReleaseResponse) Reset()                    { *m = CreateCompassReleaseResponse{} }
func (m *CreateCompassReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCompassReleaseResponse) ProtoMessage()               {}
func (*CreateCompassReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateCompassReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateCompassReleaseRequest)(nil), "compass.CreateCompassReleaseRequest")
	proto.RegisterType((*CreateCompassReleaseResponse)(nil), "compass.CreateCompassReleaseResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CompassService service

type CompassServiceClient interface {
	CreateCompassRelease(ctx context.Context, in *CreateCompassReleaseRequest, opts ...grpc.CallOption) (*CreateCompassReleaseResponse, error)
}

type compassServiceClient struct {
	cc *grpc.ClientConn
}

func NewCompassServiceClient(cc *grpc.ClientConn) CompassServiceClient {
	return &compassServiceClient{cc}
}

func (c *compassServiceClient) CreateCompassRelease(ctx context.Context, in *CreateCompassReleaseRequest, opts ...grpc.CallOption) (*CreateCompassReleaseResponse, error) {
	out := new(CreateCompassReleaseResponse)
	err := grpc.Invoke(ctx, "/compass.CompassService/CreateCompassRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CompassService service

type CompassServiceServer interface {
	CreateCompassRelease(context.Context, *CreateCompassReleaseRequest) (*CreateCompassReleaseResponse, error)
}

func RegisterCompassServiceServer(s *grpc.Server, srv CompassServiceServer) {
	s.RegisterService(&_CompassService_serviceDesc, srv)
}

func _CompassService_CreateCompassRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompassReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompassServiceServer).CreateCompassRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compass.CompassService/CreateCompassRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompassServiceServer).CreateCompassRelease(ctx, req.(*CreateCompassReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CompassService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compass.CompassService",
	HandlerType: (*CompassServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompassRelease",
			Handler:    _CompassService_CreateCompassRelease_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compass.proto",
}

func init() { proto.RegisterFile("compass.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x66, 0x6d, 0x9b, 0x98, 0x29, 0x7a, 0x18, 0x2a, 0x2e, 0xb1, 0x87, 0x50, 0x14, 0x82, 0x87,
	0x04, 0xe2, 0x1b, 0x98, 0x07, 0x10, 0xd6, 0x9b, 0xb7, 0x75, 0x19, 0x6d, 0xa0, 0xc9, 0xc6, 0xec,
	0xa6, 0x3e, 0x9e, 0xaf, 0x26, 0xd9, 0xcd, 0xe2, 0xa5, 0xd8, 0xd3, 0xfc, 0x7d, 0xf3, 0xf7, 0x7d,
	0x70, 0xa5, 0x74, 0xdb, 0x4b, 0x63, 0x8a, 0x7e, 0xd0, 0x56, 0x63, 0x3c, 0x87, 0x69, 0xba, 0x97,
	0x7d, 0x53, 0x0e, 0x74, 0x20, 0x69, 0x28, 0x58, 0x0f, 0x4a, 0x6f, 0x5d, 0x4d, 0xed, 0xe5, 0x60,
	0x4b, 0xa5, 0xbb, 0x8f, 0xe6, 0xd3, 0x17, 0x76, 0x3f, 0x0c, 0xee, 0xea, 0x81, 0xa4, 0xa5, 0xda,
	0x8f, 0x11, 0xbe, 0x4f, 0xd0, 0xd7, 0x48, 0xc6, 0xe2, 0x06, 0x56, 0xae, 0x8b, 0xb3, 0x8c, 0xe5,
	0x89, 0xf0, 0x01, 0x22, 0x2c, 0x3b, 0xd9, 0x12, 0xbf, 0x70, 0x49, 0xe7, 0xe3, 0x16, 0x92, 0xc9,
	0x9a, 0x5e, 0x2a, 0xe2, 0x0b, 0x57, 0xf8, 0x4b, 0xe0, 0x23, 0x44, 0x47, 0x79, 0x18, 0xc9, 0xf0,
	0x65, 0xc6, 0xf2, 0x75, 0x85, 0xc5, 0x74, 0x51, 0xe1, 0xc6, 0x15, 0xb5, 0xbb, 0x48, 0xcc, 0x08,
	0xe4, 0x10, 0xdb, 0xa6, 0x25, 0x3d, 0x5a, 0xbe, 0xca, 0x58, 0xbe, 0x10, 0x21, 0x9c, 0xf6, 0x7e,
	0xcb, 0xc6, 0xf2, 0x28, 0x63, 0xf9, 0xa5, 0x70, 0xfe, 0xee, 0x05, 0xb6, 0xa7, 0x1f, 0x30, 0xbd,
	0xee, 0x0c, 0x61, 0x09, 0xf1, 0xcc, 0x85, 0xfb, 0x61, 0x5d, 0xdd, 0xf8, 0xd5, 0x81, 0xa0, 0x80,
	0x0f, 0xa8, 0x6a, 0x84, 0xeb, 0x79, 0xd4, 0x2b, 0x0d, 0xc7, 0x46, 0x11, 0x2a, 0xd8, 0x9c, 0x5a,
	0x81, 0xf7, 0x45, 0x90, 0xe2, 0x1f, 0x0a, 0xd3, 0x87, 0x33, 0x28, 0x7f, 0xe7, 0x73, 0xf2, 0x16,
	0x94, 0x7c, 0x8f, 0x9c, 0x36, 0x4f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x6e, 0x73, 0x7b,
	0xea, 0x01, 0x00, 0x00,
}
