// Code generated by protoc-gen-go.
// source: compass.proto
// DO NOT EDIT!

/*
Package compass is a generated protocol buffer package.

It is generated from these files:
	compass.proto

It has these top-level messages:
	CreateCompassReleaseRequest
	CreateCompassReleaseResponse
	UpdateCompassReleaseRequest
	UpdateCompassReleaseResponse
	UpgradeCompassReleaseRequest
	UpgradeCompassReleaseResponse
*/
package compass

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hapi_release5 "k8s.io/helm/pkg/proto/hapi/release"
import hapi_chart "k8s.io/helm/pkg/proto/hapi/chart"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateCompassReleaseRequest struct {
	Chart     string             `protobuf:"bytes,1,opt,name=chart" json:"chart,omitempty"`
	Name      string             `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Namespace string             `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	Values    *hapi_chart.Config `protobuf:"bytes,4,opt,name=values" json:"values,omitempty"`
	Timeout   int64              `protobuf:"varint,5,opt,name=timeout" json:"timeout,omitempty"`
	Wait      bool               `protobuf:"varint,6,opt,name=wait" json:"wait,omitempty"`
}

func (m *CreateCompassReleaseRequest) Reset()                    { *m = CreateCompassReleaseRequest{} }
func (m *CreateCompassReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCompassReleaseRequest) ProtoMessage()               {}
func (*CreateCompassReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateCompassReleaseRequest) GetChart() string {
	if m != nil {
		return m.Chart
	}
	return ""
}

func (m *CreateCompassReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCompassReleaseRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateCompassReleaseRequest) GetValues() *hapi_chart.Config {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *CreateCompassReleaseRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *CreateCompassReleaseRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

type CreateCompassReleaseResponse struct {
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *CreateCompassReleaseResponse) Reset()                    { *m = CreateCompassReleaseResponse{} }
func (m *CreateCompassReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCompassReleaseResponse) ProtoMessage()               {}
func (*CreateCompassReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateCompassReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type UpdateCompassReleaseRequest struct {
	Name      string             `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version   int32              `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Values    *hapi_chart.Config `protobuf:"bytes,3,opt,name=values" json:"values,omitempty"`
	Namespace string             `protobuf:"bytes,4,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *UpdateCompassReleaseRequest) Reset()                    { *m = UpdateCompassReleaseRequest{} }
func (m *UpdateCompassReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateCompassReleaseRequest) ProtoMessage()               {}
func (*UpdateCompassReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateCompassReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCompassReleaseRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UpdateCompassReleaseRequest) GetValues() *hapi_chart.Config {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *UpdateCompassReleaseRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type UpdateCompassReleaseResponse struct {
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *UpdateCompassReleaseResponse) Reset()                    { *m = UpdateCompassReleaseResponse{} }
func (m *UpdateCompassReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateCompassReleaseResponse) ProtoMessage()               {}
func (*UpdateCompassReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateCompassReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

type UpgradeCompassReleaseRequest struct {
	Chart     string             `protobuf:"bytes,1,opt,name=chart" json:"chart,omitempty"`
	Name      string             `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Values    *hapi_chart.Config `protobuf:"bytes,3,opt,name=values" json:"values,omitempty"`
	Namespace string             `protobuf:"bytes,4,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *UpgradeCompassReleaseRequest) Reset()                    { *m = UpgradeCompassReleaseRequest{} }
func (m *UpgradeCompassReleaseRequest) String() string            { return proto.CompactTextString(m) }
func (*UpgradeCompassReleaseRequest) ProtoMessage()               {}
func (*UpgradeCompassReleaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpgradeCompassReleaseRequest) GetChart() string {
	if m != nil {
		return m.Chart
	}
	return ""
}

func (m *UpgradeCompassReleaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpgradeCompassReleaseRequest) GetValues() *hapi_chart.Config {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *UpgradeCompassReleaseRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type UpgradeCompassReleaseResponse struct {
	Release *hapi_release5.Release `protobuf:"bytes,1,opt,name=release" json:"release,omitempty"`
}

func (m *UpgradeCompassReleaseResponse) Reset()                    { *m = UpgradeCompassReleaseResponse{} }
func (m *UpgradeCompassReleaseResponse) String() string            { return proto.CompactTextString(m) }
func (*UpgradeCompassReleaseResponse) ProtoMessage()               {}
func (*UpgradeCompassReleaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpgradeCompassReleaseResponse) GetRelease() *hapi_release5.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateCompassReleaseRequest)(nil), "compass.CreateCompassReleaseRequest")
	proto.RegisterType((*CreateCompassReleaseResponse)(nil), "compass.CreateCompassReleaseResponse")
	proto.RegisterType((*UpdateCompassReleaseRequest)(nil), "compass.UpdateCompassReleaseRequest")
	proto.RegisterType((*UpdateCompassReleaseResponse)(nil), "compass.UpdateCompassReleaseResponse")
	proto.RegisterType((*UpgradeCompassReleaseRequest)(nil), "compass.UpgradeCompassReleaseRequest")
	proto.RegisterType((*UpgradeCompassReleaseResponse)(nil), "compass.UpgradeCompassReleaseResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CompassService service

type CompassServiceClient interface {
	CreateCompassRelease(ctx context.Context, in *CreateCompassReleaseRequest, opts ...grpc.CallOption) (*CreateCompassReleaseResponse, error)
	UpdateCompassRelease(ctx context.Context, in *UpdateCompassReleaseRequest, opts ...grpc.CallOption) (*UpdateCompassReleaseResponse, error)
	UpgradeCompassRelease(ctx context.Context, in *UpgradeCompassReleaseRequest, opts ...grpc.CallOption) (*UpgradeCompassReleaseResponse, error)
}

type compassServiceClient struct {
	cc *grpc.ClientConn
}

func NewCompassServiceClient(cc *grpc.ClientConn) CompassServiceClient {
	return &compassServiceClient{cc}
}

func (c *compassServiceClient) CreateCompassRelease(ctx context.Context, in *CreateCompassReleaseRequest, opts ...grpc.CallOption) (*CreateCompassReleaseResponse, error) {
	out := new(CreateCompassReleaseResponse)
	err := grpc.Invoke(ctx, "/compass.CompassService/CreateCompassRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compassServiceClient) UpdateCompassRelease(ctx context.Context, in *UpdateCompassReleaseRequest, opts ...grpc.CallOption) (*UpdateCompassReleaseResponse, error) {
	out := new(UpdateCompassReleaseResponse)
	err := grpc.Invoke(ctx, "/compass.CompassService/UpdateCompassRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *compassServiceClient) UpgradeCompassRelease(ctx context.Context, in *UpgradeCompassReleaseRequest, opts ...grpc.CallOption) (*UpgradeCompassReleaseResponse, error) {
	out := new(UpgradeCompassReleaseResponse)
	err := grpc.Invoke(ctx, "/compass.CompassService/UpgradeCompassRelease", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CompassService service

type CompassServiceServer interface {
	CreateCompassRelease(context.Context, *CreateCompassReleaseRequest) (*CreateCompassReleaseResponse, error)
	UpdateCompassRelease(context.Context, *UpdateCompassReleaseRequest) (*UpdateCompassReleaseResponse, error)
	UpgradeCompassRelease(context.Context, *UpgradeCompassReleaseRequest) (*UpgradeCompassReleaseResponse, error)
}

func RegisterCompassServiceServer(s *grpc.Server, srv CompassServiceServer) {
	s.RegisterService(&_CompassService_serviceDesc, srv)
}

func _CompassService_CreateCompassRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompassReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompassServiceServer).CreateCompassRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compass.CompassService/CreateCompassRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompassServiceServer).CreateCompassRelease(ctx, req.(*CreateCompassReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompassService_UpdateCompassRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompassReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompassServiceServer).UpdateCompassRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compass.CompassService/UpdateCompassRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompassServiceServer).UpdateCompassRelease(ctx, req.(*UpdateCompassReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompassService_UpgradeCompassRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeCompassReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompassServiceServer).UpgradeCompassRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compass.CompassService/UpgradeCompassRelease",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompassServiceServer).UpgradeCompassRelease(ctx, req.(*UpgradeCompassReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CompassService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compass.CompassService",
	HandlerType: (*CompassServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompassRelease",
			Handler:    _CompassService_CreateCompassRelease_Handler,
		},
		{
			MethodName: "UpdateCompassRelease",
			Handler:    _CompassService_UpdateCompassRelease_Handler,
		},
		{
			MethodName: "UpgradeCompassRelease",
			Handler:    _CompassService_UpgradeCompassRelease_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compass.proto",
}

func init() { proto.RegisterFile("compass.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xc7, 0xe5, 0xee, 0x17, 0x3b, 0x15, 0x1c, 0xac, 0xad, 0xb0, 0xd2, 0x45, 0x5a, 0x45, 0x80,
	0xa2, 0x1c, 0x62, 0xba, 0xa8, 0x1c, 0x0a, 0x27, 0xf6, 0x01, 0x40, 0x41, 0x5c, 0xb8, 0x99, 0x74,
	0x48, 0x23, 0xed, 0xc6, 0x21, 0xf6, 0x86, 0x03, 0xea, 0x85, 0x47, 0x00, 0x71, 0xe1, 0x86, 0x78,
	0x10, 0x1e, 0x82, 0x57, 0xe0, 0x1d, 0xb8, 0xa2, 0x38, 0x76, 0x09, 0x28, 0xbb, 0x0b, 0xa5, 0xa7,
	0x78, 0x3c, 0xa3, 0x99, 0xdf, 0x7f, 0x66, 0x1c, 0xb8, 0x9e, 0xc8, 0x55, 0x21, 0x94, 0x8a, 0x8a,
	0x52, 0x6a, 0x49, 0x47, 0xd6, 0xf4, 0xbc, 0x33, 0x51, 0x64, 0xbc, 0xc4, 0x25, 0x0a, 0x85, 0xee,
	0xdb, 0x04, 0x79, 0x37, 0x8d, 0x2f, 0x39, 0x13, 0xa5, 0xe6, 0x89, 0xcc, 0x5f, 0x65, 0xa9, 0x75,
	0x4c, 0x53, 0x29, 0xd3, 0x25, 0xf2, 0xda, 0x2d, 0xf2, 0x5c, 0x6a, 0xa1, 0x33, 0x99, 0xdb, 0xdc,
	0xfe, 0x57, 0x02, 0x87, 0x8b, 0x12, 0x85, 0xc6, 0x45, 0x53, 0x24, 0x6e, 0xb2, 0xc6, 0xf8, 0x7a,
	0x8d, 0x4a, 0xd3, 0x09, 0x0c, 0x4c, 0x4e, 0x46, 0x66, 0x24, 0x18, 0xc7, 0x8d, 0x41, 0x29, 0xf4,
	0x73, 0xb1, 0x42, 0xb6, 0x67, 0x2e, 0xcd, 0x99, 0x4e, 0x61, 0x5c, 0x7f, 0x55, 0x21, 0x12, 0x64,
	0x3d, 0xe3, 0xf8, 0x75, 0x41, 0x43, 0x18, 0x56, 0x62, 0xb9, 0x46, 0xc5, 0xfa, 0x33, 0x12, 0xec,
	0xcf, 0x69, 0x54, 0xf3, 0x46, 0x26, 0x5d, 0xb4, 0x30, 0xbc, 0xb1, 0x8d, 0xa0, 0x0c, 0x46, 0x3a,
	0x5b, 0xa1, 0x5c, 0x6b, 0x36, 0x98, 0x91, 0xa0, 0x17, 0x3b, 0xb3, 0xae, 0xfb, 0x46, 0x64, 0x9a,
	0x0d, 0x67, 0x24, 0xb8, 0x16, 0x9b, 0xb3, 0xff, 0x04, 0xa6, 0xdd, 0x02, 0x54, 0x21, 0x73, 0x85,
	0x94, 0xc3, 0xc8, 0x76, 0xca, 0x68, 0xd8, 0x9f, 0x1f, 0x34, 0xa5, 0x5d, 0xfb, 0x5c, 0xbc, 0x8b,
	0xf2, 0x3f, 0x12, 0x38, 0x7c, 0x5e, 0x9c, 0x6e, 0x6c, 0x89, 0x13, 0x4f, 0x5a, 0xe2, 0x19, 0x8c,
	0x2a, 0x2c, 0x55, 0x26, 0x73, 0xd3, 0x93, 0x41, 0xec, 0xcc, 0x96, 0xf0, 0xde, 0x4e, 0xe1, 0xbf,
	0xb5, 0xb0, 0xff, 0x47, 0x0b, 0x6b, 0xa1, 0xdd, 0x58, 0x97, 0x15, 0xfa, 0x9e, 0xd4, 0x19, 0xd3,
	0x52, 0x9c, 0xfe, 0xf7, 0xf0, 0xaf, 0x4e, 0xe5, 0x53, 0xb8, 0xb5, 0x81, 0xe9, 0x92, 0x32, 0xe7,
	0x3f, 0x7a, 0x70, 0xc3, 0xe6, 0x7a, 0x86, 0x65, 0x95, 0x25, 0x48, 0x3f, 0x11, 0x98, 0x74, 0x2d,
	0x0d, 0xbd, 0x1d, 0xb9, 0xa7, 0xb7, 0xe5, 0x51, 0x78, 0x77, 0x76, 0x44, 0x35, 0xa4, 0xfe, 0xf1,
	0xbb, 0x6f, 0xdf, 0x3f, 0xec, 0x71, 0x3f, 0xe4, 0xd5, 0x11, 0xbf, 0x50, 0xa8, 0xf8, 0xdb, 0x8b,
	0xf3, 0xb9, 0x7b, 0xc4, 0xf6, 0xf2, 0xfc, 0x84, 0x84, 0xf4, 0x33, 0x81, 0x49, 0xd7, 0xa0, 0x5b,
	0x70, 0x5b, 0xd6, 0xb3, 0x05, 0xb7, 0x6d, 0x5b, 0xfc, 0x47, 0x06, 0xee, 0x81, 0x77, 0xf4, 0xf7,
	0x70, 0xbc, 0x19, 0x60, 0xcd, 0xf8, 0x85, 0xc0, 0x41, 0xe7, 0x98, 0x68, 0xbb, 0xfc, 0xe6, 0xd5,
	0xf2, 0xee, 0xee, 0x0a, 0xb3, 0x98, 0x0f, 0x0d, 0xe6, 0xb1, 0x77, 0xef, 0x1f, 0x30, 0xcd, 0xd6,
	0x9d, 0x90, 0xf0, 0xf1, 0xf8, 0x85, 0xfb, 0x75, 0xbe, 0x1c, 0x9a, 0xdf, 0xdd, 0xfd, 0x9f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xb4, 0xdc, 0x7e, 0x5c, 0x5b, 0x05, 0x00, 0x00,
}
